### ISSUE TITLE
If not in /opt/Z

### ISSUE THREAD

**Issue by rahulnusiss** [arandilopez/z-eves#2]
/z-eves/Z-Eves/system$ ./z-eves-gui.sh
xset:  bad font path element (#3), possible causes are:
    Directory does not exist or has wrong permissions
    Directory missing fonts.dir
    Incorrect font server address or syntax
./z-eves-gui.sh: 24: exec: /opt/Z/bin/python: not found

**Comment by arandilopez** [comment]
Hi @rahulnusiss, let me replicate this to solve it. Someone else also report me the issue a months ago but He didn't send a PR. If you can solve it, please send a PR.

**Comment by arandilopez** [comment]
Oh and yes, the paths in some files are static to `/opt/Z`. I don't know why... I just upload this from a version I found years ago in a ugly webpage. And because that page closed, I uploaded this repo to back it up.

**Comment by tshi206** [comment]
Hahaha, student from UOA studying in a postgrad course and YES our lecturer tells us to use this shit. Tbh I will never touch it again once the course finishes.

**Comment by arandilopez** [comment]
Take a beer man 🍺. You deserve a follow @tshi206
